### ISSUE TITLE
Authentication Activated and show password feature

### ISSUE THREAD

**Issue by llaville** [underground-works/clockwork-app#31]
With Chrome extension screenshot provided, we cannot see an eye to show/hide password

![auth_chrome_extension](https://user-images.githubusercontent.com/364342/73859945-2177ef80-483b-11ea-94a8-28696d5fe3a7.png)

While it's ok with native WebUI

![doctrine-audit-bundle-demo_local___clockwork_app_auth](https://user-images.githubusercontent.com/364342/73859994-2d63b180-483b-11ea-8711-94f319d540ff.png)

Just re-tested with Firefox (cache cleared), and it seems the password protection protocol is not recognized

**Comment by llaville** [comment]
I confirm again that only Firefox extension did not follow passord protection. 
Here is an example with a Symfony Yaml config file : 

```yaml
clockwork:
    web_dark_theme: true
    enable: true
    web: true
    authentication: true
    authentication_password: VerySecretPassword
```

That produced such results : 

![firefox_auth_issue](https://user-images.githubusercontent.com/364342/73922601-b9241f00-48c9-11ea-8e3e-0a982a7a7f42.png)

We should have "The site requires authentication" prompt as with WebUI and Chrome extension.
We current get http request results .

Confirmed by WebUI API
